name: dev-check-repository

on: [push]

jobs:
  build-maven-test:
    runs-on: ubuntu-latest

    container:
      image: maven:3.8.6-jdk-8
      options: --user root -v ${{ github.workspace }}:/home/maven/:rw

    steps:
      - uses: actions/checkout@v1
      - name: Run build maven
        run: mvn -Duser.home=/var/maven clean install
      - name: Run maven test
        run: mvn -Duser.home=/var/maven test